apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-prod
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mk95devops/ubiquitous-robot-argo.git
    path: application
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../nodejs/env/prod.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-prod

  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true

